server:
  port: ${port:8766}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/layui?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: job-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
feign:
  hystrix:
    enabled: true