server:
  port: ${port:8764}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yingjingxiaomu/Little-monster
          searchPaths:
          label: master
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
